sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: '2.7'
      env: FOO=1
      stage: test

    - python: '2.7'
      env: FOO=2
      stage: test

    - python: '2.7'
      env: DEPLOY=1
      stage: deploy

cache:
  pip: true
  directories:
  - $HOME/capnp


install:
  - pip install -U pip # so that we can use wheels
  - pip install cython>=0.25

script:
  - echo foo $FOO
  - echo deploy $DEPLOY
  - python setup.py build_ext --inplace
  - py.test
