sudo: false
language: python

matrix:
  fast_finish: true
  include:

    - stage: test
      python: '2.7'
      env: FOO=1

    - stage: deploy
      sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      install:
        - docker pull $DOCKER_IMAGE
        script:
          - docker run --rm -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-wheels.sh
          - ls wheelhouse/

cache:
  pip: true
  directories:
  - $HOME/capnp


install:
  - pip install -U pip # so that we can use wheels
  - pip install cython>=0.25

script:
  - echo foo $FOO
  - echo deploy $DEPLOY
  - python setup.py build_ext --inplace
  - py.test
